# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout SmartHub repo
      uses: actions/checkout@v2
      with:
        repository: SmartHub-Io/SmartHub
        path: develop
      
    - name: install mono
      run: |
        sudo apt install gnupg ca-certificates
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
    
    - name: install mono
      run: sudo apt install mono-devel
      
    - name: Chocolatey Action
      uses: crazy-max/ghaction-chocolatey@v1.2.2
      with:
        # Arguments to pass to Chocolatey
        args: -h
      
    - name: install docfx
      run: choco install docfx
      
    - name: init docfx
      run: docfx init -q
      
    - name: meta docfx
      run: docfx metadata docfx_project/docfx.json
      
    - name: docs docfx
      run: docfx build docfx_project/docfx.json -o docs      
      
    # Publish generated site using GitHub Pages
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages
