name: Docs CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout SmartHub-Docs
      uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run build

      # publish to github pages
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.1
      with:
        target_branch: gh-pages
        build_dir: dist
        commit_message: Documentation update
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
